# Generated by Django 5.2.1 on 2025-05-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(verbose_name='Телефон')),
                ('post', models.CharField(verbose_name='Должность')),
                ('resume', models.TextField(verbose_name='Резюме')),
                ('portfolio_link', models.URLField(blank=True, verbose_name='Ссылка на портфолио')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
