# Generated by Django 5.2.1 on 2025-05-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='post',
        ),
    ]
