# Generated by Django 5.2.1 on 2025-05-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInfo', '0002_remove_members_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='managers_images/')),
                ('post', models.CharField(verbose_name='Должность')),
                ('email', models.CharField()),
            ],
        ),
    ]
