# Generated by Django 5.2.1 on 2025-05-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInfo', '0003_management'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'Руководители', 'verbose_name_plural': 'Руководители'},
        ),
    ]
