# Generated by Django 5.2.1 on 2025-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('year', models.IntegerField(default=2025, verbose_name='Курс')),
                ('module', models.CharField(choices=[(1, '1 модуль'), (2, '2 модуль'), (3, '3 модуль'), (4, '4 модуль')], default=1, max_length=1, verbose_name='Модуль')),
                ('discipline', models.CharField(default='', max_length=200, verbose_name='Тематика работы, предмет в вузе')),
                ('is_team', models.BooleanField(default=False, verbose_name='GIS-анализ')),
                ('description', models.TextField(blank=True, default='', verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
