# Generated by Django 5.2.1 on 2025-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalProgramm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='module',
            field=models.IntegerField(choices=[(1, '1 модуль'), (2, '2 модуль'), (3, '3 модуль'), (4, '4 модуль')], verbose_name='Модуль'),
        ),
    ]
