# Generated by Django 5.2.1 on 2025-05-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalProgramm', '0002_alter_educationprogram_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationprogram',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
