# Generated by Django 5.2.1 on 2025-05-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalProgramm', '0003_alter_educationprogram_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationprogram',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
    ]
