# Generated by Django 5.2.1 on 2025-05-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalProgramm', '0004_alter_educationprogram_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='course',
            field=models.IntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], default=3, verbose_name='Курс'),
        ),
    ]
