# Generated by Django 5.2.1 on 2025-05-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalProgramm', '0005_educationprogram_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='link',
            field=models.URLField(blank=True, default='https://deziiign.com/teams/hsedesignfutures', verbose_name='Ссылка на проект'),
        ),
    ]
