# Generated by Django 5.2.1 on 2025-06-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalProgramm', '0006_educationprogram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='discipline',
            field=models.CharField(default='', max_length=200, verbose_name='Название дисциплины'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='is_team',
            field=models.BooleanField(default=False, verbose_name='Командный'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='link',
            field=models.URLField(blank=True, default='https://hsedesign.ru/designer/LOUD', verbose_name='Ссылка на проект'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Год Обучения'),
        ),
    ]
