# Generated by Django 5.2.1 on 2025-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalProgramm', '0007_alter_educationprogram_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='is_team',
            field=models.BooleanField(default=False, verbose_name='GIS-анализ'),
        ),
    ]
